config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]
  resource :events
  resources :event_attendees, only: [:create]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/even_attendee.rb
class EvenAttendee < ApplicationRecord
  belongs_to :event, class_name: 'Event'
  belongs_to :attendee, class_name: 'User'
end

app/models/event.rb
class Event < ApplicationRecord
    validates :place, :time, presence:true
    belongs_to :creator, class_name: 'User', foreign_key: 'creator_id'
    has_many :even_attendees, dependent: :destroy    
    has_many :attendees, through: :even_attendees, source: :attendee
    scope :today, -> { where("DATE(events.created_at) = ?", Date.today) }
    scope :past, -> { where("DATE(events.created_at) < ?", Date.today) }
    scope :future, -> { where("DATE(events.created_at) > ?", Date.today) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events, foreign_key: 'creator_id',  dependent: :destroy
  has_many :even_attendees, foreign_key: 'attendee_id'
  has_many :attended_events, through: :even_attendees, source: :event
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/even_attendee_controller.rb
class EvenAttendee < ApplicationRecord
    belongs_to :event, class_name: 'Event'
    belongs_to :attendee, class_name: 'User'
  end
  

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index,:show]


  def index
    @events = Event.all
    @events_today = Event.today 
    @events_past = Event.past 
    @events_future = Event.future
  end

  def show 
      @event = Event.find_by(params[:id])
  end

  def new
    @event = Event.new
  end
    
  def create
    @event = current_user.events.build(new_event_params)
    if @event.save
      flash[:success] = 'Event Created Successfully'
      redirect_to events_path 
    else
      render :new
    end
  end

  private
  def new_event_params
    params.require(:event).permit(:place, :time)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController  
    before_action :authenticate_user!
    def show
        @events = current_user.events
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/index.html.erb
<button><%= link_to 'Create New Event', new_events_path%></button>
<button><%= link_to 'All My Events', root_path%></button>

<% if user_signed_in?%>
    <button><%= link_to 'SignOut', destroy_user_session_path %></button>
    <button><%= link_to 'UserProfile', user_path(current_user)%></button>
<%end%>

<h1>All Events</h1>

<h2>Today's Events</h2>
<%if @events_today.any?%>
    <% @events_today.each do |event|%>
        <button><%= link_to event.place, events_path(event)%></button>
    <%end%>
<%else%>
    <p>No Events Today</p>
<%end%>

<h2>Future Events</h2>

<% if @events_future.any?%>
    <% @events_future.each do |event|%>
        <button><%= link_to event.place, events_path(event)%></button>   
    <%end%>
<%else%>
    <P>No Future Events Found</P>
<%end%>

<h2>Past Events</h2>
<% if @events_past.any?%>
    <% @events_past.each do |event|%>
        <button><%= link_to event.place, events_path(event)%></button>
    <%end%>
<%else%>
    <p>No Past Events Found</p>
<%end%>

app/views/events/new.html.erb
<%if user_signed_in? %>
    <button><%= link_to 'User_profile', user_path(current_user)%></button>
    <button><%= link_to 'SignOut', destroy_user_session_path%></button>
<%end%>
<br>

<%if @event.errors.any?%>
    <div id="error-explanation">
        <h2><%= pluralize(@event.errors.count, 'errors')%>prohibited the user from save</h2>
        <ul>
            <%=@event.errors.full_messages.each do |msg|%>
                <li><%=msg%></li>
            <%end%>
        </ul>
    </div>
<%end%>


<h1>Create Your Next Another Event 💥</h1>
<%= form_with model: @event do |f| %>
    <%= f.label 'Please Enter the location'%>
    <%= f.text_field :place%>
    <br>
    <br>
    <%= f.label 'Please Enter Timings Of The Event'%>
    <%= f.text_field :time%>
    <br>
    <br>
    <%=f.submit 'Create The Event'%>
<%end%>

app/views/events/show.html.erb
<button><%= link_to  "All Events", root_path %></button>
<button><%= link_to 'Create events', new_events_path %></button>
<% if user_signed_in? %>
  <button><%= link_to  "Sign out", destroy_user_session_path %></button>
  <button><%= link_to  "Profile", user_path(current_user) %></button>
<% end %>
<h1>
  <%= @event.place %>
</h1>
<h2>Date</h2>
<%= @event.place %>
<h2>Place</h2>
<%= @event.place %>
<%= form_with url: '/join', method: :post do |f|%>
  <%= f.hidden_field :event_id, value: @event.id %>
  <br>
  <button><%= f.submit 'Join this events' %></button>
<% end %>
<h2>Attendees</h2>
<% if @event.attendees.any? %>
  <ul>
    <% @event.attendees.each do |attendee| %>
      <li><%= attendee.email %></li>
    <% end %>
  </ul>
<% else %>
  <p>No attendees for this event.</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<h1>THESE ARE ALL LIST OF THE EVENTS YOU CREATE</h1>

<h1>Here You Can See All Events YOU Created</h1>
<% @events.each do |event| %>
    <h3>
        <%= event.place%>
    </h3>
    <h4>
        <%= event.time%>
    </h4>
<%end%>